@baseUrl = http://localhost:3000 

### Read all films
GET {{baseUrl}}/films

### Read all films with minimum-duration of 140min
GET {{baseUrl}}/films/?minimum-duration=140

### Try to read films with wrong minimum-duration
GET {{baseUrl}}/films/?minimum-duration=0

###Create a film
POST {{baseUrl}}/films
Content-Type: application/json

{
     "title": "Gardien de la galaxie ",
        "duration": "149" ,
        "budget": "250" , 
        "link" : "https://fr.disney.be/films/ ", 

}

### GET all
GET {{baseUrl}}/films
Content-Type: application/json

### GET minimum 
GET {{baseUrl}}/films?minimum-duration=80
Content-Type: application/json
 